### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by Derwaan** [cursemeslowly/devrantia#4]
How about opening a [Gitter](https://gitter.im/) for discussing this project more easily?
Or any other possibilities (Slack,...)

**Comment by cursemeslowly** [comment]
Sure we can communicate more on a chat app.
Which one is more common and easy for average dev?
I am fine with any tool.

**Comment by Jay9596** [comment]
Gitter is a better option as you can use it with GitHub login, it's more convenient this way.
